import { QuartzConfig } from "../../quartz/cfg"
import {
  AddFavicons,
  AfterArticle,
  AliasRedirects,
  AllTagsPage,
  Assets,
  CrawlLinks,
  CreatedModifiedDate,
  FixFootnotes,
  FrontMatter,
  GitHubFlavoredMarkdown,
  HTMLFormattingImprovement,
  Latex,
  NotFoundPage,
  ObsidianFlavoredMarkdown,
  RecentPostsPage,
  RemoveDrafts,
  Static,
  SyntaxHighlighting,
  TableOfContents,
  TagAcronyms,
  TagPage,
  TextFormattingImprovement,
  TroutOrnamentHr,
  Twemoji,
  WrapNakedElements,
  addAssetDimensionsFromSrc,
  ColorVariables,
  ContentIndex,
  ContentPage,
  ComponentResources,
  rehypeCustomSpoiler,
  rehypeCustomSubtitle,
  PopulateContainers,
} from "../../quartz/plugins"

const config: QuartzConfig = {
  configuration: {
    pageTitle: "Oscar the Zettelkasten",
    enablePopovers: true,
    analytics: null,

    baseUrl: "turntrout.com",
    ignorePatterns: ["private", "templates/**", ".obsidian"],
    defaultDateType: "published",
    navbar: {
      pages: [
        { title: "About me", slug: "/about" },
        { title: "My research", slug: "/research" },
        { title: "All posts", slug: "/posts" },
        { title: "Open source", slug: "/open-source" },
      ],
    },
  },
  plugins: {
    transformers: [
      FrontMatter(),
      CreatedModifiedDate({
        priority: ["frontmatter", "filesystem"],
      }),
      TextFormattingImprovement(),
      Twemoji(),
      SyntaxHighlighting({
        theme: {
          light: "github-light",
          dark: "github-dark",
        },
        keepBackground: false,
      }),
      ObsidianFlavoredMarkdown({
        enableInHtmlEmbed: true,
        parseArrows: false,
        enableCheckbox: true,
      }),
      GitHubFlavoredMarkdown({ enableSmartyPants: false }),
      FixFootnotes(),
      HTMLFormattingImprovement(),
      Latex({ renderEngine: "katex" }),
      CrawlLinks({ lazyLoad: true, markdownLinkResolution: "shortest" }),
      TagAcronyms(),
      TroutOrnamentHr(),
      AfterArticle(),
      AddFavicons(),
      ColorVariables(),
      rehypeCustomSpoiler(),
      rehypeCustomSubtitle(),
      TableOfContents(),
      WrapNakedElements(),
      addAssetDimensionsFromSrc(),
    ],
    filters: [RemoveDrafts()],
    emitters: [
      AliasRedirects(),
      ComponentResources(),
      ContentPage(),
      PopulateContainers(),
      TagPage(),
      AllTagsPage(),
      RecentPostsPage(),
      ContentIndex({
        enableSiteMap: true,
        enableRSS: true,
      }),
      Assets(),
      Static(),
      NotFoundPage(),
    ],
  },
}

export default config
